// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: RobotContainer.

package frc.robot;

import frc.robot.commands.*;
import frc.robot.subsystems.*;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command.InterruptionBehavior;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;

import java.util.Map;

import edu.wpi.first.wpilibj.GenericHID;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.shuffleboard.BuiltInLayouts;
import edu.wpi.first.wpilibj.shuffleboard.BuiltInWidgets;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardLayout;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.shuffleboard.WidgetType;
import edu.wpi.first.wpilibj2.command.button.POVButton;
import frc.robot.subsystems.*;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 * This class is where the bulk of the robot should be declared.  Since Command-based is a
 * "declarative" paradigm, very little robot logic should actually be handled in the {@link Robot}
 * periodic methods (other than the scheduler calls).  Instead, the structure of the robot
 * (including subsystems, commands, and button mappings) should be declared here.
 */
public class RobotContainer {

  private static RobotContainer m_robotContainer = new RobotContainer();

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
// The robot's subsystems
    public final DriveSubsystem m_driveSubsystem = new DriveSubsystem();

// Joysticks
private final XboxController accessoryController = new XboxController(0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

  
  // A chooser for autonomous commands
  SendableChooser<Command> m_chooser = new SendableChooser<>();

  /**
  * The container for the robot.  Contains subsystems, OI devices, and commands.
  */
  private RobotContainer() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    // Smartdashboard Subsystems


    // SmartDashboard Buttons
    SmartDashboard.putData("Autonomous Command", new AutonomousCommand());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SMARTDASHBOARD
    ShuffleboardLayout placementLayout = Shuffleboard.getTab("REEFSCAPE")
       .getLayout("Selector ", BuiltInLayouts.kGrid)
       .withPosition(2,0)
       .withSize(2, 4)
       .withProperties(Map.of("Label position", "HIDDEN")); // hide labels for commands
    
    placementLayout.addBoolean("0-0",()->true).withPosition(0,3).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);
    placementLayout.addBoolean("1-0",()->false).withPosition(1, 3).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);
    placementLayout.add("L2L", false).withPosition(0, 2).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);
    placementLayout.add("L2R", false).withPosition(1, 2).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);
    placementLayout.add("L3L", false).withPosition(0, 1).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);
    placementLayout.add("L3R", false).withPosition(1, 1).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);
    placementLayout.add("L4L", false).withPosition(0,0).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);
    placementLayout.add("L4R", false).withPosition(1, 0).withWidget(BuiltInWidgets.kBooleanBox).withSize(1,1);


  // ShuffleboardTab mainTab = Shuffleboard.getTab("REEFSCAPE");
  // mainTab.addBoolean("0-0", () -> true)
  //   .withWidget(BuiltInWidgets.kBooleanBox)
  //   .withPosition(1, 1);
 
  // mainTab.addBoolean("1-0", () -> false)
  //  .withWidget(BuiltInWidgets.kBooleanBox)
  //  .withPosition(1, 2);
  
  //  mainTab.addBoolean("2-0", () -> false)
  //  .withWidget(BuiltInWidgets.kBooleanBox)
  //  .withPosition(1, 3);
  
     
    // Shuffleboard.getTab("Configuration")
    //         .add("Max Speed", 1)
    //         .withWidget("Number Slider")
    //         .withPosition(1, 1)
    //         .withSize(2, 1)
    //         .getEntry();
   // SmartDashboard.putBoolean("0-0", true);
    //SmartDashboard.putBoolean("1-0", false);
    // SmartDashboard.putBoolean("2-0", false);
    // SmartDashboard.putBoolean("3-0", false);
    // SmartDashboard.putBoolean("0-1", false);
    // SmartDashboard.putBoolean("1-1", false);
    // SmartDashboard.putBoolean("2-1", false);
    // SmartDashboard.putBoolean("3-1", false);
    // Configure the button bindings
    configureButtonBindings();

    // Configure default commands
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SUBSYSTEM_DEFAULT_COMMAND

    // Configure autonomous sendable chooser
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    m_chooser.setDefaultOption("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    SmartDashboard.putData("Auto Mode", m_chooser);
  }

  public static RobotContainer getInstance() {
    return m_robotContainer;
  }

  /**
   * Use this method to define your button->command mappings.  Buttons can be created by
   * instantiating a {@link GenericHID} or one of its subclasses ({@link
   * edu.wpi.first.wpilibj.Joystick} or {@link XboxController}), and then passing it to a
   * {@link edu.wpi.first.wpilibj2.command.button.JoystickButton}.
   */
  private void configureButtonBindings() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
// Create some buttons
final POVButton pOVButtonLeft = new POVButton(accessoryController, 270, 0);        
pOVButtonLeft.onTrue(new SelectPlacement(270).withInterruptBehavior(InterruptionBehavior.kCancelSelf));
                        
final POVButton pOVButtonRight = new POVButton(accessoryController, 90, 0);        
pOVButtonRight.onTrue(new SelectPlacement(90).withInterruptBehavior(InterruptionBehavior.kCancelSelf));
                        
final POVButton pOVButtonDown = new POVButton(accessoryController, 180, 0);        
pOVButtonDown.onTrue(new SelectPlacement(180).withInterruptBehavior(InterruptionBehavior.kCancelSelf));
                        
final POVButton pOVButtonUp = new POVButton(accessoryController, 0, 0);        
pOVButtonUp.onTrue(new SelectPlacement(0).withInterruptBehavior(InterruptionBehavior.kCancelSelf));
                        


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=BUTTONS
            
  }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
public XboxController getAccessoryController() {
      return accessoryController;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

  /**
   * Use this to pass the autonomous command to the main {@link Robot} class.
   *
   * @return the command to run in autonomous
  */
  public Command getAutonomousCommand() {
    // The selected command will be run in autonomous
    return m_chooser.getSelected();
  }
  

}

